### ISSUE TITLE
Update 8 bug

### ISSUE THREAD

**Issue by rubenheymans** [DellAquila/FlexSplines#9]
My flex water pipelines are bugged. I opened the game without the mods and after update 8.2 I have unremovable pipe connections. Any idea how I can delete them?
![image](https://github.com/DellAquila/FlexSplines/assets/2543870/e4e00d8c-b479-4906-b451-65bd2d2bef23)

**Comment by DellAquila** [comment]
Hey!!! Try that mod one time, to see if works: https://ficsit.app/mod/RemoveIndicator

**Comment by rubenheymans** [comment]
thanks I tried the mod and it seems to work, but now I have to redo all my pipes so I won't be using this mod anymore
